name: 'PHP_CodeSniffer PHPCBF coding standards fixer'
description: 'phpcbf to check and fix code against defined PHP coding standards'
author: 'GE Tracker'
inputs:
  installed_paths:
    description: 'Setting the installed standard paths'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
